name: ✨ Feature
description: Proposer une nouvelle fonctionnalité
title: "[FEATURE] "
labels:
  - "type: feature"
body:
  - type: textarea
    id: problem
    attributes:
      label: Problème
      description: Quel problème cherche-t-on à résoudre ?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solution proposée
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Critères d'acceptation
      placeholder: |
        - [ ] ...
        - [ ] ...
        - [ ] ...
    validations:
      required: true
